### ISSUE TITLE
训练时出现的一个问题

### ISSUE THREAD

**Issue by zaixuyinanwang** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#10]
layers.append(block(self.inplanes, planes, stride, downsample, att_position[0], att_dim=att_dim))
IndexError: list index out of range。
这个问题怎么解决呢？att_position是什么，后面的序号又有什么作用？

**Comment by ZilinGao** [comment]
> layers.append(block(self.inplanes, planes, stride, downsample, att_position[0], att_dim=att_dim))
> IndexError: list index out of range。
> 这个问题怎么解决呢？att_position是什么，后面的序号又有什么作用？

你好，感谢对GSoP工作的关注。

att_position是用来控制GSoP模块插入的位置及类型的参数。
att_position控制一个stage中的不同block是否被插入GSoP模块: 
https://github.com/ZilinGao/Global-Second-order-Pooling-Convolutional-Networks/blob/68264e29acd122540315ec6e78040e4665560b78/main.py#L131 

att_position控制GSoP的类型(i.e., channel, position, fusion)：https://github.com/ZilinGao/Global-Second-order-Pooling-Convolutional-Networks/blob/68264e29acd122540315ec6e78040e4665560b78/main.py#L116

抱歉回复的太晚了。虽然提问时间已经过去比较久了，希望这篇回复可以给其他有需要的人提供一些帮助。
