### ISSUE TITLE
部分源码未完全给出

### ISSUE THREAD

**Issue by cui-wenju** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#12]
你好，模型具体的部分源码什么时候给出呢

**Comment by ZilinGao** [comment]
> 你好，模型具体的部分源码什么时候给出呢

你好，

GSoP实现过程参见：
https://github.com/ZilinGao/Global-Second-order-Pooling-Convolutional-Networks/blob/68264e29acd122540315ec6e78040e4665560b78/torchvision/models/resnet.py
