### ISSUE TITLE
关于参数

### ISSUE THREAD

**Issue by lejunXTS** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#14]
在MPNCOV.py文件中，
 if iterN < 2:
            der_NSiter = 0.5*(der_postCom.bmm(I3 - A) - A.bmm(der_sacleTrace))报错，der_sacleTrace这个参数提示未定义，请问这个参数该在哪里定义，感谢！

**Comment by ZilinGao** [comment]
> 在MPNCOV.py文件中，
> if iterN < 2:
> der_NSiter = 0.5*(der_postCom.bmm(I3 - A) - A.bmm(der_sacleTrace))报错，der_sacleTrace这个参数提示未定义，请问这个参数该在哪里定义，感谢！

@lejunXTS  Thanks for your reminder! The file has been fixed, please refer to [here](https://github.com/ZilinGao/Global-Second-order-Pooling-Convolutional-Networks/blob/master/torchvision/models/MPNCOV/python/MPNCOV.py#L76) for detail.
