### ISSUE TITLE
大佬您好，请问您给出了GSoP模块代码了吗，我没有找到欸~

### ISSUE THREAD

**Issue by tjutzdd** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#3]
谢谢大佬帮助，以及分享源码！！！

**Comment by ZilinGao** [comment]
GSoP模块部分在这里：https://github.com/ZilinGao/Global-Second-order-Pooling-Convolutional-Networks/blob/master/torchvision/models/resnet.py#L95

**Comment by tjutzdd** [comment]
谢谢前辈！！！刚入门，非常感谢您的指导！！！

**Comment by ZilinGao** [comment]
@tjutzdd 
前辈不敢当～ 解决了问题就好～
