### ISSUE TITLE
如何训练？

### ISSUE THREAD

**Issue by lenlea** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#4]
您好，请问您在训练的时候冻结原来的参数了吗？
我现在有一个问题：因为我实验室只有一块gpu，当我自己从头开始训练一个模型与从别人训练好的模型预训练，出来的结果相差了20个点，请问您对这个问题有什么看法吗？模型结构都是一样的。求指导

**Comment by ZilinGao** [comment]
@lenlea 
你好，我做的实验都是从头开始训练的，所以没有冻结参数。

对于你描述的问题，我不知道我理解的对不对：你现在做了两个实验，实验1: backbone + GSoP ~ training from scratch(all layers); 实验2: backbone + GSoP ~ fine-tuning(all layers). 二者所用backbone的架构，学习率设置等完全一致。二者最终性能相差20%。是这样么？

可不可以具体说一下你是怎么实现的，比如用了什么backbone, GSoP模块的嵌入位置。如果可以的话，贴一下嵌入GSoP模块这部分的代码。此外，不知道你用的数据库是什么？如果是很小的数据库可能预训练是很有必要的。

如果我在第二段中描述的问题是对的，那请再贴一下相关的实验结果，比如: 
1. backbone ~ finetuning 
2. backbone + GSoP ~ finetuning
3. backbone ~ training from scratch
4. backbone + GSoP ~ training from scratch

**Comment by lenlea** [comment]
非常谢谢您的回答，还有一个问题，没找到关于position atten？

**Comment by ZilinGao** [comment]
@lenlea 
你好，现在的代码中只放了channel attention的代码，position attention的代码将会在近日更新上传～

**Comment by ZilinGao** [comment]
@lenlea 
你好，position attention的代码已经上传更新，感谢关注～

**Comment by lenlea** [comment]
谢谢您！
请问您在考虑模块插入的时候，是不是做了很多实验才得出的结果？我理解的是插入了四块？不知道对不对

**Comment by ZilinGao** [comment]
@lenlea 
你好，关于GSoP模块的嵌入位置及数目，我们利用ResNet26架构，在ImageNet-1K的子数据集ImageNet-1/4上进行了Ablation study，详细的实验结果见论文中Table 4.

实际使用中，模块嵌入的数目：
论文中提出了两个网络GSoP-Net1和GSoP-Net2, GSoP-Net1中对ResNet中的每个stage的末端都嵌入了一个GSoP模块，所以是4个；但在GSoP-Net2中，最后一个stage没有采用GSoP模块，而是利用了iSQRT-COV，所以是3个。
