### ISSUE TITLE
您好，我在别的任务上使用out = MPNCOV.CovpoolLayer(x)，有时候会出现-inf

### ISSUE THREAD

**Issue by zpkosmos** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#5]
代码如下：
out = MPNCOV.CovpoolLayer(x)
a = torch.min(out)
我输入的x是一个16x64x48x48的张量，16是batchsize，64是通道数，48x48是hxw
不同的x经过MPNCOV.CovpoolLayer后，我发现out的最小值有时候会是-inf，有时候又不是，请问您有没有遇到过类似的情况，能否提供什么建议吗？

**Comment by ZilinGao** [comment]
@zpkosmos 
你好，MPNCOV.CovpoolLayer(x)是在计算不同通道之间的协方差，只有简单的矩阵乘法操作，所以应该不会在计算协方差时得到-inf。请问你是否有观察输入该层的特征的分布？x中是否已经有-inf了？

**Comment by zpkosmos** [comment]
@ZilinGao 谢谢，的确是之前的特征出现了-inf，是我考虑欠佳，多谢
