### ISSUE TITLE
video classification on UCF101

### ISSUE THREAD

**Issue by Tiacy** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#6]
Thank you for your nice work !
How can i use this model in video classification on UCF101.
Look forward to your reply!
thanks again.

**Comment by ZilinGao** [comment]
@Tiacy 
Hi, Tiacy~ We did not conduct experiments on video dataset. But I would like to share some thoughts on the video task with you.

In my view, if GSoP is applied to video task,  there is two options: 
1. Independently operates GSoP module on each frame
2. Build a 3d-GSoP module

For the first option, it can be easily realized by current GSoP module with cycle struct on temporal dimension. 
And for the second option,  we can build a 3d-GSoP module for one video clip. It still faces the choice  on  attention dimension.  We can stimulate the feature on channel dimension or on channel&temporal dimension. In many influential work[non-local, i3d] on video task, the temporal dimension is operated similarly to spatial dimension. So, maybe stimulating along channel dimension is a more appropriate choice. In this case, the module should be: 

    def chan_att_3d(self, out):
        out = self.relu_normal(out)
        out = self.conv3d_for_DR(out)
        out = self.bn3d_for_DR(out)
        out = self.relu(out)

        [bs, c, n, h, w] = out.size() #n: temporal dimension
        out = out.view(bs, c, n, h*w) #bsxnxhxw ==> bsxnx(hw)
        out = MPNCOV.CovpoolLayer(out) # bsxcxnx(hw) ==> bsxcxc
        out = out.view(bs, c, n, 1).contiguous() # bsxcxcx1

        out = self.row_bn(out)
        out = self.row_conv_group(out) # bsx512x1x1

        out = self.fc_adapt_channels_3d(out) #bsxC_inx1x1x1
        out = self.sigmoid(out) #NxC_inx1x1x1

        return out

There are just some of my simple ideas, if you have any thoughts, please feel free to discuss.

Zilin Gao

**Comment by Tiacy** [comment]
Thank you very much for your help, these help is very important to me !
I am a newcomer in the field of video recognition, and my thoughts are very similar to yours. If I have new ideas, I will communicate with you as soon as possible.
Thank you again for your thoughts and time !

**Comment by ZilinGao** [comment]
@Tiacy 
If you have some new ideas or confusions, I'd be glad to discuss with you. And I'm looking forward to the GSoP performance on video task. If GSoP obtains results on video recognition, please let me know. Thank you.

Best Regards,
Zilin

**Comment by sazio** [comment]
Hey @ZilinGao and @Tiacy ! Just found this issue and I was wondering whether there's any advancement in this direction, I'm somehow working on similar stuff in this moment !

**Comment by ZilinGao** [comment]
@sazio Thanks for your attention! We made an attempt on temporal covariance matrix for video, which adopts a temporal channel-wise attention served as one of temporal relation modules. 

[Temporal-attentive Covariance Pooling Networks for Video Recognition. In NeurIPS, 2021.](https://proceedings.neurips.cc/paper/2021/file/70efdf2ec9b086079795c442636b55fb-Paper.pdf)

**Comment by sazio** [comment]
@ZilinGao Amazing ! Thank you very much, I didn't find that paper + implementation before :)
