### ISSUE TITLE
Have you found which type of fuse in attention is better?

### ISSUE THREAD

**Issue by Awenjie10** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#7]
Hello, Thank your work! I found that there are 4 types of fuse in attention, but I would like to know which type is better? concatenate? or add like residual learning? Have you done experiments for four types?

**Comment by ZilinGao** [comment]
@Awenjie10 Sorry for the late reply. 

We conduct the experiments on the fusion method, please refer to Tab4(b) for detail ,  [[paper]][1].

[1]:http://openaccess.thecvf.com/content_CVPR_2019/papers/Gao_Global_Second-Order_Pooling_Convolutional_Networks_CVPR_2019_paper.pdf
