### ISSUE TITLE
 Second-order

### ISSUE THREAD

**Issue by henbucuoshanghai** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#8]
why using  Second-order  the resout is better???

**Comment by ZilinGao** [comment]
@henbucuoshanghai hello.

Second-order pooling could capture the global information by calculating the correlation between any two channels. And MPN-COV estimates a more robust second-order feature by matrix power normalization. You could read [this paper](https://openaccess.thecvf.com/content_ICCV_2017/papers/Li_Is_Second-Order_Information_ICCV_2017_paper.pdf)  for more detail. Thanks.
