### ISSUE TITLE
Is the second-order block suitable for ResNet18 ResNet34 network?

### ISSUE THREAD

**Issue by wangxinyue11** [ZilinGao/Global-Second-order-Pooling-Convolutional-Networks#9]
I see that the second-order block is not used in the resnet network with a lower number of layers in your source code. Is it not good? Why is it not good?

**Comment by ZilinGao** [comment]
@wangxinyue11 Hello, Xinyue. Sorry for the late reply. 

We conducted the experiments on ResNet18 (on ImageNet-1/4K). It also superiors to the baseline. And we did not evaluate GSoP performance on ResNet-34. 

The results on ImageNet-1K shown in paper are all based on ResNet-50, so we only release the ResNet-50 backbone. If you are interested in GSoP performance on other depth of ResNet, you could deploy the network by changing the ResNet block number in each stage easily. 

Thanks for your attention! :)
